services:
  - type: web
    name: spares-ageing-dashboard
    env: python
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    pythonVersion: "3.12.7"
  
